repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: b969e2851312ca2b24bbec879ba4954341d1bd12  # frozen: v0.15.5
    hooks:
      # Lint + auto-fix safe issues
      - id: ruff
        args: [--fix]
      # Format code
      - id: ruff-format

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: d0e12caebb2ab0ee8bf98181c8bfe9702bca103d  # frozen: v1.105.0
    hooks:
      - id: terraform_fmt
